apiVersion: v1
kind: Service
metadata:
  name: ratings-data-service-cluster-ip-service
spec:
  selector:
    component: ratings-data-service-pod
  ports:
    - name: http
      port: 8083 # targetPort se não definido usa o mesmo valor do port. targetPort: 8083 nodePort: 30083
  type: ClusterIP #NodePort

