apiVersion: v1
kind: Service
metadata:
  name: ratings-data-service-cluster-ip-service
  annotations:
    author: DhiegoDuarte
    email: dhiegoduarte@gmail.com
    company: ClaroBR
  labels:
    application: ratings-data-service
    revision: TODO_COMO_COLOCAR_O_COMMIT_AQUI #4c511f16ef2644854d04cabebfcecc82be0eb04f
    env: stage
    version: "1.0.0"
    owner: movies-squad
spec:
  selector:
    component: ratings-data-service-pod
  ports:
    - name: http
      port: 8083 # targetPort se não definido usa o mesmo valor do port. targetPort: 8083 nodePort: 30083
  type: ClusterIP #NodePort

